Updated to readme schematic images
adonno/tagreader pull request #89
Opened 2021-01-10 16:49 UTC by rosscullen

Hi @adonno 
Here's my small contribution back for all your help. 
Updated Fritzing diagram and PNG image on readme - new layout to match the positioning in the case. Labels, DIN etc all uploaded based on the one I received. Also inverted tc/rx as they appeared incorrectly (as per my recent discord message).
Also included an image of my completed layout to match the schematic as best as possible.

Hope its of use. I could as some FAQ as well if its of help to readme? EG adding switched to Lovelace to control LED, buzzer etc. Also getting rid of the red LED on reader.

Thanks. R

2021-01-17 06:14 UTC, jesserockz requested changes
You seem to have the buzzer wired up to `5v` and `GND` in your schematic, but it should be `D7` and `GND`?

2021-01-17 09:43 UTC, rosscullen commented
> You seem to have the buzzer wired up to `5v` and `GND` in your schematic, but it should be `D7` and `GND`?

Will take a look @jesserockz thanks for the feedback

2021-01-17 10:14 UTC, rosscullen commented
Thanks for feedback @jesserockz you were right on the money. Please can review again and see if we're good to go! Thanks :-)

2021-01-20 17:04 UTC, adonno commented
D1 and D2 inverted ? 
D1 should go to  SCL
and D2 to SDA

2021-01-20 21:15 UTC, rosscullen commented
> D1 and D2 inverted ?
> D1 should go to SCL
> and D2 to SDA

Thanks @adonno changes made. FZZ file and PNG updated. Also added updated labels on LED Board.

2021-01-20 22:03 UTC, adonno commented
looks fine for me, @magnusoverli  @jesserockz does one of you guys mind having one last look and merge if you are ok with it?

2021-01-20 22:21 UTC, jesserockz commented on README.md
> -![Photo of schematics](Schematics/tag_reader_schematics_v2.png)
I know this is not exactly your fault @rosscullen as the repo was already set this way. 
But there is no point in creating version numbers for files in git... You should just be overriding the old file with a new one. Git is the version manager. cc @adonno @magnusoverli

2021-01-20 22:41 UTC, merged